name: Enforce PR Title Format

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  enforce-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          NUMBER=${{ github.event.pull_request.number }}
          
          echo "PR Title: $TITLE"
          
          if [[ "$TITLE" != *"(#${NUMBER})"* ]]; then
            echo "::error ::PR title must include '(#${NUMBER})' to be used as squash commit message"
            exit 1
          fi
