name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello and welcome!  
            Thanks for opening your first issue here. We appreciate your input and will review it as soon as possible.  
            In the meantime, please make sure you’ve followed the issue template and provided all necessary details.

          pr-message: |
            Thanks for your first pull request!  
            We’re excited to have you contribute. A maintainer will review your PR soon.  
            Please make sure your code follows our contribution guidelines and passes all checks.  
            Again, welcome aboard and thank you!
