name: Lint Lua

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck .
