name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  SITE_URL: https://spiware.blackhex.xyz

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap.xml
        run: |
          mkdir -p docs
          echo '<?xml version="1.0" encoding="UTF-8"?>' > docs/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> docs/sitemap.xml
          find docs -name "*.html" | sed 's|docs/||' | while read page; do
            echo "  <url><loc>${{ env.SITE_URL }}/${page}</loc></url>" >> docs/sitemap.xml
          done
          echo '</urlset>' >> docs/sitemap.xml

      - name: Generate robots.txt
        run: |
          echo "User-agent: *" > docs/robots.txt
          echo "Allow: /" >> docs/robots.txt
          echo "Sitemap: ${{ env.SITE_URL }}/sitemap.xml" >> docs/robots.txt

      - name: Create .nojekyll
        run: touch docs/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
